language:
  - cpp

matrix:
    include:
    - os: linux
      sudo: true
      env: 
        - INSTALL_DEP=""
        - CMAKE_GENERATOR="Unix Makefiles"
        - TEST_DIR="./tests"
        - RUN_TESTS="./UnitTests"

    - os: osx
      sudo: true
      env: 
        - INSTALL_DEP=""
        - CMAKE_GENERATOR="Unix Makefiles"
        - TEST_DIR="./tests"
        - RUN_TESTS="./UnitTests"
        
#    - os: windows
#      env: 
#        - INSTALL_DEP="choco install visualstudio2019community"
#        - CMAKE_GENERATOR="Visual Studio 16 2019"
#        - TEST_DIR="tests\\Release"
#        - RUN_TESTS="UnitTests.exe"

before_install:
    - ${INSTALL_DEP}
  
script:
    - mkdir build
    - cd build
    - cmake ../trunk -G "${CMAKE_GENERATOR}"
    - cmake --build . --target ALL_BUILD --config Release
    - cd ${TEST_DIR}
    - ${RUN_TESTS}

notifications:
  email: false