language:
  - cpp

matrix:
    include:
    - os: windows
      sudo: true
      env: 
        - CMAKE_CONFIG="cmake ../trunk -G \"Unix Makefiles""
        - TEST_DIR="./tests"
        - RUN_TESTS="./UnitTests"

    - os: windows
      env: 
        - MATRIX_EVAL="choco install visualstudio2019community"
        - CMAKE_CONFIG="cmake ../trunk -G \"Visual Studio 16 2019\""
        - TEST_DIR="tests\\Release"
        - RUN_TESTS="UnitTests.exe"

script:
    - mkdir build
    - cd build
    - "$CMAKE_CONFIG"
    - cmake --build . --target ALL_BUILD --config Release
    - cd "$TEST_DIR"
    - $RUN_TESTS

notifications:
  email: false