sudo: true

language:
  - cpp

matrix:
    include:
        os: windows
        script:
            - "mkdir build"
            - "cd build"
            - "cmake ../trunk -G \"Visual Studio 16 2019\""
            - "cmake --build . --target ALL_BUILD --config Release"
            - "cd tests\\Release"
            - "UnitTests.exe"

        os: linux
        script:
            - "mkdir build"
            - "cd build"
            - "cmake ../trunk -G \"Ninja\""
            - "cmake --build . --target ALL_BUILD --config Release"
            - "cd tests"
            - "./UnitTests"

notifications:
  email: false
