language:
  - cpp

matrix:
    include:
    - os: linux
      sudo: true
      env: 
        - INSTALL_DEP=""
        - SET_ENV=""
        - CMAKE_GENERATOR="Unix Makefiles"
        - TEST_DIR="./tests"
        - RUN_TESTS="./UnitTests"

    - os: osx
      sudo: true
      env: 
        - INSTALL_DEP=""
        - SET_ENV=""
        - CMAKE_GENERATOR="Unix Makefiles"
        - TEST_DIR="./tests"
        - RUN_TESTS="./UnitTests"
        
    - os: windows
      env: 
        - INSTALL_DEP="choco install visualstudio2019community --package-parameters \"--includeRecommended\""
        - SET_ENV="type C:\ProgramData\chocolatey\logs\chocolatey.log"
#        - SET_ENV="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
        - CMAKE_GENERATOR="Visual Studio 16 2019"
        - TEST_DIR="tests\\Release"
        - RUN_TESTS="UnitTests.exe"

before_install:
    - ${INSTALL_DEP}
    - eval ${SET_ENV}

script:
    - mkdir build
    - cd build
    - cmake ../trunk -G "${CMAKE_GENERATOR}"
    - cmake --build . --target UnitTests --config Release
    - cd ${TEST_DIR}
    - ${RUN_TESTS}

notifications:
  email: false