language:
  - cpp

matrix:
    include:
    - os: linux
      sudo: true
      env: 
        - CMAKE_GENERATOR="Unix Makefiles"

    - os: osx
      sudo: true
      env: 
        - CMAKE_GENERATOR="Unix Makefiles"

    - os: windows
      env: 
        - CMAKE_GENERATOR="Visual Studio 15 2017"

script:
    - mkdir build
    - cd build
    - cmake ../trunk -G "${CMAKE_GENERATOR}"
    - cmake --build . --target UnitTests --config Release
    - cd bin
    - ./UnitTests

notifications:
  email: false