sudo: true
  
language:
  - cpp

before_install:
 - pwd
 - sudo wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - sudo tar xf eigen-eigen-5a0156e40feb.tar.gz

script:
  - mkdir build
  - cd build
  - cmake ../trunk -DGTest_DIR:STRING="../../googletest-release-1.8.0" -DEigen3_DIR:STRING="../../eigen-eigen-5a0156e40feb" -DExprtk_DIR:STRING="../trunk/dependencies/exprtk" -DRTree_DIR:STRING="../trunk/dependencies/RTree" 
  - make
  - cd tests
  - ./UnitTests

notifications:
  email: false