language:
  - cpp

before_install:
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0
 - pwd
 
script:
  - cd trunk
  - mkdir build
  - cd build
  - cmake -DGTest_DIR:STRING="../../googletest-release-1.8.0" .. 
  - make
  - cd tests
  - ./UnitTests

notifications:
  email: false