language:
  - cpp

matrix:
    include:
    - os: linux
      sudo: true
      env: 
        - CMAKE_GENERATOR="Unix Makefiles"
        - TEST_DIR="bin"
        - RUN_TESTS="./UnitTests"

    - os: osx
      sudo: true
      env: 
        - CMAKE_GENERATOR="Unix Makefiles"
        - TEST_DIR="bin"
        - RUN_TESTS="./UnitTests"

    - os: windows
      env: 
        - CMAKE_GENERATOR="Visual Studio 15 2017"
        - TEST_DIR="bin"
        - RUN_TESTS="UnitTests.exe"

script:
    - mkdir build
    - cd build
    - cmake ../trunk -G "${CMAKE_GENERATOR}"
    - cmake --build . --target UnitTests --config Release
    - cd ${TEST_DIR}
    - ${RUN_TESTS}

notifications:
  email: false